model_config:
  model_name: "databricks/dolly-v2-3b"
  tokenizer_name: "databricks/dolly-v2-3b"
  lora: true
  lora_path: "path/to/lora/model"

generate_config:
  do_sample: true
  num_beams: 4
  max_new_tokens: 512
  length_penalty: 1.5
  no_repeat_ngram_size: 3
  early_stopping: true
  return_instruction_text: false