# model config
save_name: "lora-dolly-v2-3b"
model_name_or_path: "databricks/dolly-v2-3b"
output_dir: "./results"
load_8bit: false

# optimizer config
lr: 5.0e-5
weight_decay: 0.0

# training config
seed: 42
num_epochs: 2
patience: 2
gradient_accumulation_steps: 2
gradient_checkpointing: true

# data config
data_path: "mini_instruction_data.json"
max_length: 512
train_batch_size: 4
eval_batch_size: 4
test_size: 0.2

# LoRA config
lora: True
lora_r: 8
lora_alpha: 32
lora_dropout: 0.1