model:
  name: "databricks/dolly-v2-3b"
  output_dir: "saved-runs"
  load_in_8bit: false
  save_name: "finetuned-dolly-v2-3b"

optim:
  lr: 2.0e-5
  min_lr: 0
  weight_decay: 0.0
  warmup_steps: 100

train:
  seed: 42
  num_epochs: 3
  patience: 3
  gradient_accumulation_steps: 4
  gradient_checkpointing: true
  push_to_hub: false

data:
  path: "data-name.json"
  max_length: 512
  train_batch_size: 4
  eval_batch_size: 4
  test_size: 0.2

lora:
  active: True
  ckpt_path: null
  r: 8
  alpha: 32
  dropout: 0.1